name: SB Engine Question tab
description: Ask about something here for SB Engine.
labels: [question]
body:
  - type: textarea
    attributes:
      label: What is your question?
    validations:
      required: true